name: Publish images to Docker Hub
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Python script for processing Docker images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip3 install github3.py
        python3 .github/workflows/scripts/docker-image.py
